### ISSUE TITLE
Minor style updates

### ISSUE THREAD

**Issue by germanny** [HigherEducation/WordPressMeta#5]
1. Can you make the individual repeater fields stand out just a tad. Visually, they are so similar and run so tightly together that is is difficult to see individual repeater items at a glance. You could do something as simple as some `padding-top` or `border-top`, or do a number or alternating colors or whatever you want.
2. Make the draggable area a little bigger so it is easier to grab. Also doing the little cross cursor would be grand here too.

This is a little bit easier to use because the grab area is bigger and the number/grey area helps show where a field begins and ends:
![image](https://user-images.githubusercontent.com/1421416/28583292-4aa05190-712e-11e7-95a0-86c0776ed8a0.png)

**Comment by jasoncomes** [comment]
Added this visual. Plus the move cursor so its visually 1000000 times better.

<img width="974" alt="screenshot 2017-08-03 16 19 54" src="https://user-images.githubusercontent.com/5714439/28944300-bbb01600-7867-11e7-8f22-a0cbe3d5f215.png">

Hide the remove button, once you hover the repeater box comes into focus. 
<img width="416" alt="screenshot 2017-08-03 16 20 06" src="https://user-images.githubusercontent.com/5714439/28944304-bf445c72-7867-11e7-9fe5-510542c6ed78.png">

**Comment by germanny** [comment]
YASSSSSS!!!!
